# Generated by Django 4.0.7 on 2022-10-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_matchingfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companiesname',
            name='mf_id',
        ),
    ]
