# Generated by Django 4.0.7 on 2022-10-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_remove_companiesname_mf_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=60)),
                ('mf_name', models.CharField(max_length=60)),
                ('cp_id', models.CharField(max_length=60)),
                ('mf_id', models.CharField(max_length=60)),
            ],
        ),
    ]
