# Generated by Django 4.0.7 on 2022-10-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_jointablemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companiesname',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mutualfunds',
            name='id',
        ),
        migrations.AlterField(
            model_name='companiesname',
            name='cp_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mutualfunds',
            name='mf_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
